apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidecar-security
  name: sidecar-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-security
  template:
    metadata:
      labels:
        app: sidecar-security
    spec:
      containers:
      - image: bikertales/sidecar-security:6652c1a1785244536e1d134bb78269878ac7a732
        name: sidecar-security
        imagePullPolicy: Always
        env: 
        - name: CUSTOMER_DATA_SVC
          value: sidecar-security-data-svc
        - name: CUSTOMER_DATA_SVC_Port
          value: "50051"  
        - name: FRAUD_CHECK_SVC
          value: fraud-check-svc
        - name: FRAUD_CHECK_SVC_Port
          value: "8090"  
      - image: kennethreitz/httpbin
        name: origin-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidecar-security
  name: origin-httpbin
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: sidecar-security   
